apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  selector:
    matchLabels:
      app: backend-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
      - name: backendjs
        image: chataum/justa-project-backend:1.0
        ports:
        - containerPort: 8000