apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: backend-deploy
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: frontend-deploy
spec:
  selector:
    app: frontend-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200      