apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.network/frontend: "true"
    io.kompose.service: backend
  name: backend
spec:
  containers:
    - env:
        - name: DB
          value: mongodb://root:globant@pg-db:27017/
        - name: PORT
          value: "8000"
      image: backend
      name: backendjs
      ports:
        - containerPort: 8000
      resources: {}
  hostname: backendjs
  restartPolicy: OnFailure
status: {}
