apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendjs
spec:
  selector:
    matchLabels:
      app: frontendjs
  replicas: 1
  template:
    metadata:
      labels:
        app: frontendjs
    spec:
      containers:
      - name: frontendjs
        image: chataum/justa-project-frontend:1.0
        #imagePullPolicy: Never
        ports:
        - containerPort: 4200
