apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontendjs
spec:
  selector:
    app: frontendjs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  